Support go embed
moov-io/base pull request #164
Opened 2021-05-10 09:30 UTC by alovak

2021-05-10 13:26 UTC, alovak commented on database/migrator.go
> +func RunMigrations(logger log.Logger, config DatabaseConfig, migrationsSource source.Driver) error {
If we want to keep `base` package compatible with old versions of the service, I can create `RunMigrationsWithSource` to support `pkger` migrations as well.

2021-05-10 15:39 UTC, InfernoJJ requested changes

2021-05-10 15:42 UTC, alovak commented on config/config.go
> +		s.logger.LogErrorf("loading default config file using pkger: %w", err)
Yeap. My idea here, if we want to keep `pkger` ... for backward compatibility?, just to ignore the error. And log it instead. I would prefer to get rid of `pkger` then we don't need it.

2021-05-10 15:43 UTC, alovak commented on database/migrator.go
> +	ver, _, err := m.Version()
Based on current output I had no idea what was the version before migration and what's the version after. It was not clear for me if migrations run at all. That's why I decided to add some information to migrations.

2021-05-10 15:55 UTC, alovak commented on config/config_test.go
> +	Custom  string
Just to test that we read a custom field from the a custom file.

2021-05-10 21:13 UTC, InfernoJJ commented on config/config_test.go
> +	Custom  string
The `App` is the custom file?

2023-05-31 17:31 UTC, adamdecaf commented
Replaced by https://github.com/moov-io/base/pull/302

2023-05-31 17:31 UTC, closed without merging