add WithPrefix for prefixed logging
moov-io/base pull request #183
Opened 2021-08-11 20:12 UTC by hampgoodwin

# Changes

- Add interface WithPrefix
- Implement logger.WithPrefix method, which users underlying go-kit/log.WithPrefix()
- Add test for new WithPrefix

# Why

I need to set prefix values at construction of a logger, or upon entering a a function set function-relevant values in the logger which will persist after serially logging. WithPrefix allows for setting values which will always be logged when .Log() is called, until that logger is cleaned up.

# Example use

```go
func (s *service) Get(id string, requestID string) (*Widget, error) {
contextualLogger := s.logger.WithPrefix(log.Fields{"function": log.String("service.Get"), "request_id": log.String(request_id)})

contextualLogger.Debug().Log("getting widget from store")
widget, err := s.store.Get(id)
if err !=nil {
  contextualLogger.Error().Log("something bad happened")
  return nil, err
}

contextualLogger.Debug().Log("returning widget")
return widget, nil
}
```

2021-08-11 20:16 UTC, hampgoodwin commented
Hrmm, I didn't touch anything in the database/* dir, how am I bringing down the test coverage?

2021-08-11 21:01 UTC, InfernoJJ requested changes
I don't understand the purpose of it? It sounds like just `.With` but mutates versus returning a thread safe new context?

2021-08-11 21:22 UTC, adamdecaf commented on CHANGELOG.md
> +- log: added WithPrefix method for persistence contextual logging
https://github.com/moov-io/base/pull/182 is part of this release too, right?

2021-08-11 21:43 UTC, hampgoodwin commented
Closing for now.
After discussion with @InfernoJJ we think there is a different issue that causes .With() to not work as intended on larger subsets of contexts. I'll work on reproducing in a test, and then I'll PR some fixes.

Ah,, #182 will be included the next release  unless someone beats me to it.

2021-08-11 21:43 UTC, closed without merging

2021-08-12 14:53 UTC, hampgoodwin commented
Ok, some further digger and testing revealed the logger package .With works as intended. The issue was a cli log parser that I run which was de-duping values.